name: Populate Devcontainers
on: [push]
permissions:
  contents: write
jobs:
  populate:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run populate-devcontainers.sh
        run: ./scripts/populate-devcontainers.sh
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update populated devcontainers [skip ci]"
          file_pattern: 'populated/devcontainer.*.json'
  publish-devcontainers:
    needs: populate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Run publish-devcontainers.sh
        run: ./scripts/publish-devcontainers.sh
