name: Populate Devcontainers
on: [push]
permissions:
  contents: write
jobs:
  populate:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Run populate-devcontainers.sh
        run: ./scripts/populate-devcontainers.sh
      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update populated devcontainers [skip ci]"
          file_pattern: 'populated/devcontainer.*.json'
